# This is a full-line comment describing the entire file.

misc:
   seed: 0

classification:
  data_base_path: "/home/datasets" # Path to the classification dataset base directory.
  target_class_list:
    - "deer"
    - "horse"
    - "zebra"
  linear_classifier_type: "SGDClassifier" # Specifies the type of linear classifier to use.
  lambda_aligns: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  sensitivityanalysis_lambdas: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

# --- CONCEPT CONFIGURATIONS ---
# This section defines the paths for various concepts.
concept:
  base_path: "/home/concept"
  target_folders:
    - "deer/coat"
    - "horse/horse_skin"
    - "zebra/stripes"
  random_folder: "/home/concept/random"

hyperparameters:
  learning_rate: 1e-03
  epochs: 30
  batch_size: 64
  
