# This is a full-line comment describing the entire file.

# Path to the caltech dataset
misc:
   seed: 0

classification:
  data_base_path: "/mnt/sdd/caltech_training" # Path to the classification dataset base directory.
  target_class_list:
    - "001.Black_footed_Albatross"
    - "002.Laysan_Albatross"
    - "003.Sooty_Albatross"
    - "004.Groove_billed_Ani"
    - "005.Crested_Auklet"
    - "006.Least_Auklet"
    - "007.Parakeet_Auklet"
    - "008.Rhinoceros_Auklet"
    - "009.Brewer_Blackbird"
    - "010.Red_winged_Blackbird"


  linear_classifier_type: "SGDClassifier" # Specifies the type of linear classifier to use.
  lambda_aligns: [ 0.5, 0.6, 0.7, 0.8]

# --- CONCEPT CONFIGURATIONS ---
# This section defines the paths for various concepts.
concept:
  base_path: "/mnt/sdd/parts"
  target_folders:
    - "001.Black_footed_Albatross/beak"
    - "002.Laysan_Albatross/beak"
    - "003.Sooty_Albatross/beak"
    - "004.Groove_billed_Ani/beak"
    - "005.Crested_Auklet/beak"
    - "006.Least_Auklet/beak"
    - "007.Parakeet_Auklet/beak"
    - "008.Rhinoceros_Auklet/beak"
    - "009.Brewer_Blackbird/beak"
    - "010.Red_winged_Blackbird/beak"
    
  random_folder: "/home/concept/random"

hyperparameters:
  learning_rate: 1e-03
  epochs: 30
  batch_size: 64
  
  
