# This is a full-line comment describing the entire file.

# Path to the caltech dataset
misc:
   seed: 0

classification:
  data_base_path: "/mnt/sdd/caltech_training" # Path to the classification dataset base directory.
  target_class_list:
    - '001.Black_footed_Albatross'
    - '002.Laysan_Albatross'
    - '003.Sooty_Albatross'


  linear_classifier_type: 'SGDClassifier' # Specifies the type of linear classifier to use.
  lambda_aligns: [ 0.5, 0.6, 0.7, 0.8]

# --- CONCEPT CONFIGURATIONS ---
# This section defines the paths for various concepts.
concept:
  base_path: '/mnt/sdd/parts'
  target_folders:
    - '001.Black_footed_Albatross/beak'
    - '002.Laysan_Albatross/beak'
    - '003.Sooty_Albatross/beak'
    
  random_folder: '/home/concept/random'

hyperparameters:
  learning_rate: 1e-03
  epochs: 30
  batch_size: 64
  
# --- MODEL CONFIGURATIONS ---
# This section specifies model-specific settings, including layers to train.  
recalibration:
  override_retraining: true
  layers_to_train:
    vgg16:
      - 'features.5'
      # - 'features.7'
      # - 'features.12'
      # - 'features.13'
      # - 'features.14'
      # - 'features.15'
      # - 'features.21'

    inception_v3:
      - 'Mixed_6e.branch1x1.conv'
      # - 'Mixed_6e.branch7x7_1.conv'
      # - 'Mixed_7a.branch3x3_1.conv'

    resnet50:
      - 'layer4.0.conv1'
      # - 'layer4.0.conv2'
      # - 'layer4.1.conv1'

    mobilnet_v3_small:
      - 'features.5.block.0.0'
      # - 'features.6.block.0.0'

    mobilenet_v3_large:
      - 'features.5.block.0.0'
      # - 'features.6.block.0.0'
  #lambda_aligns_recalib: [0.5, 0.6, 0.7, 0.8] 
  lambda_aligns_recalib: [0.5]
# --- END OF CONFIGURATIONS ---

# Note all the XAI images can be captured here for before after comparison
xai_before_after:
  integrated_gradients: true
  grad_cam: true
  lime: true
  image_path:
    #Chass 0     Class 1        Class 2
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0001_796111.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0003_796136.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0005_796090.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0006_796065.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0007_796138.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0008_796083.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0010_796097.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0014_89.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0016_796067.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0019_796104.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0023_796059.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0024_796089.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0025_796057.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0032_796115.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0033_796086.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0035_796140.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0036_796127.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0038_212.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0039_796132.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0040_796066.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0041_796108.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0042_796071.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0045_796129.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0047_796064.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0049_796063.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0050_796125.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0053_796109.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0058_796074.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0060_796076.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0064_796101.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0065_796068.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0067_170.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0068_796135.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0069_796139.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0071_796113.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0076_417.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0077_796114.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0078_796126.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0079_796122.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0080_796096.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0082_796121.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0085_92.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0086_796062.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0088_796133.jpg'
    - '/mnt/data/caltech_training/train/001.Black_footed_Albatross/Black_Footed_Albatross_0089_796069.jpg'  #Class1
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/Laysan_Albatross_0002_1027.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0005_565.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0006_702.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0012_696.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0013_910.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0017_614.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0018_492.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0023_1059.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0025_571.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0028_643.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0029_482.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0033_658.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0034_628.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0037_699.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0039_924.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0040_472.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0042_801.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0044_784.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0047_619.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0049_918.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0050_870.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0053_543.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0055_570.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0056_500.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0059_488.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0060_777.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0061_563.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0064_674.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0065_809.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0070_788.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0071_792.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0075_668.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0076_671.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0079_506.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0080_821.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0081_800.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0083_756.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0085_564.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0088_883.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0091_602.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0092_834.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0094_1013.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0096_673.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0098_621.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0099_869.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0100_735.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0103_504.jpg'
    - '/mnt/data/caltech_training/train/002.Laysan_Albatross/aysan_Albatross_0104_630.jpg'    #Class 2
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0001_1071.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0002_796395.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0003_1078.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0005_796342.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0006_796390.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0007_796372.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0010_796355.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0013_796402.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0014_796373.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0016_1075.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0017_796349.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0019_796391.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0021_796339.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0022_796398.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0023_796401.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0024_1161.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0025_796361.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0029_796357.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0030_1122.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0031_1066.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0032_1149.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0033_1128.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0038_1065.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0040_796375.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0042_1210.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0045_1162.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0046_1211.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0048_1130.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0049_796350.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0050_796351.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0054_796347.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0057_796354.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0058_796360.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0063_1101.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0064_796343.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0065_796367.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0066_796382.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0067_796376.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0068_796353.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0070_796346.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0071_1116.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0072_796371.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0073_1171.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0074_1221.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0075_796352.jpg'
    - '/mnt/data/caltech_training/train/003.Sooty_Albatross/Sooty_Albatross_0076_796365.jpg'
