general:
  batch_size: 32
  num_workers: 4
  dataset_path: '/home/balanced_dataset/train'

models:
  inception_v3:
    model_path: '/mnt/sdd/basics/balanced_training/inception_v3/inception_v3.pth'
    layers_to_perturb:
    #Layers specific and sensitive to background
    #Class 0 background
    #  - 'maxpool2'
    #  - 'Mixed_5d.branch3x3dbl_3.conv'
    #  - 'Mixed_6e.branch_pool.conv'
    #  - 'Mixed_7a.branch7x7x3_2.conv'
    #  - 'Mixed_7c.branch1x1.conv'
    #Class 1 background
      - 'Conv2d_4a_3x3.conv'
      - 'Mixed_5c.branch5x5_1.conv'
      - 'Mixed_6e.branch7x7dbl_3.conv'
      - 'Mixed_7a.branch7x7x3_2.conv'
      - 'Mixed_7c.branch3x3dbl_3a.conv'
    #Class 2 background
  
  vgg16:
    model_path: '/mnt/sdd/basics/balanced_training/vgg16/vgg16.pth'
    layers_to_perturb:
      - 'features.28' # Last convolutional layer in VGG16 
      - 'features.23' # Middle convolutional layer in VGG16
      - 'features.16' # Early convolutional layer in VGG16

  resnet50:
    model_path: '/mnt/sdd/basics/balanced_training/resnet50/resnet50.pth'
    layers_to_perturb:
      - 'layer4.2.conv3' # Last convolutional layer in ResNet50
      - 'layer3.5.conv3' # Middle convolutional layer in ResNet50
      - 'layer1.2.conv2' # Early convolutional layer in ResNet50

  mobilenet_v3_small:
    model_path: '/mnt/sdd/basics/balanced_training/mobilenet_v3_small/mobilenet_v3_small.pth'
    layers_to_perturb:
      - 'features.15.0.conv.2' # Last convolutional layer in MobileNetV3 Small
      - 'features.10.0.conv.2' # Middle convolutional layer in MobileNetV3 Small
      - 'features.3.0.conv.2'  # Early convolutional layer in MobileNetV3 Small

  mobilenet_v3_large:
    model_path: '/mnt/sdd/basics/balanced_training/mobilenet_v3_large/mobilenet_v3_large.pth'
    layers_to_perturb:
      - 'features.16.0.conv.2' # Last convolutional layer in MobileNetV3 Large
      - 'features.11.0.conv.2' # Middle convolutional layer in MobileNetV3 Large
      - 'features.4.0.conv.2'  # Early convolutional layer in MobileNetV3 Large


