"""
Unit + CLI/integration tests for lean_recalibration/main_recalib_custom_by_loading_cav.py.

Unlike main_store_cav.py, this script DOES expose reusable ``main()``/``main_multiclass()``
functions, but they still require a fully-populated CAVRegistry, DataLoaders, etc. to run --
so the full pipeline is still exercised via subprocess (the ``run_script`` fixture), reusing
CAV stores pre-populated ONCE per session by ``main_store_cav.py`` (see
``populated_single_cav_store`` / ``populated_multi_cav_store`` in conftest.py). Pure helper
functions (``_extract_images_and_labels``, ``load_model_manifest``, ``build_class_concepts_map``,
``_resolve_layer_combos``, ``_load_target_cavs``, ``_load_class_concept_cavs``) are unit-tested
in-process for speed and precision.

The CLI/integration tests use the *_recalib fast config variants (single VGG layer,
override_retraining=True) generated by generate_test_data.py, which collapse
``_resolve_layer_combos()`` to exactly one combination so the real gradient-descent training
loop stays fast; the full 7-combination math is covered directly by
``TestResolveLayerCombos.test_no_groups_three_layers_gives_seven_combos`` instead.
"""

import json
import os

import pytest
import torch

import main_recalib_custom_by_loading_cav as recalib
from cav_registry import CAVRegistry

from helpers import constants as C


class _CollectingLogger:
    def __init__(self):
        self.lines = []

    def info(self, msg):
        self.lines.append(("info", msg))

    def warning(self, msg):
        self.lines.append(("warning", msg))

    def error(self, msg):
        self.lines.append(("error", msg))


# ---------------------------------------------------------------------------
# _extract_images_and_labels
# ---------------------------------------------------------------------------
@pytest.mark.unit
class TestExtractImagesAndLabels:
    def test_tuple_batch_splits_images_and_labels(self):
        imgs = torch.zeros(2, 3, 4, 4)
        labels = torch.tensor([0, 1])
        out_imgs, out_labels = recalib._extract_images_and_labels((imgs, labels))
        assert out_imgs is imgs
        assert out_labels is labels

    def test_bare_tensor_batch_has_no_labels(self):
        imgs = torch.zeros(2, 3, 4, 4)
        out_imgs, out_labels = recalib._extract_images_and_labels(imgs)
        assert out_imgs is imgs
        assert out_labels is None

    def test_single_element_list_batch_has_no_labels(self):
        imgs = torch.zeros(2, 3, 4, 4)
        out_imgs, out_labels = recalib._extract_images_and_labels([imgs])
        assert out_imgs is imgs
        assert out_labels is None


# ---------------------------------------------------------------------------
# load_model_manifest
# ---------------------------------------------------------------------------
@pytest.mark.unit
class TestLoadModelManifest:
    def test_missing_file_raises_file_not_found(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            recalib.load_model_manifest(str(tmp_path / "no_such_manifest.json"))

    def test_valid_manifest_parses_concepts(self, tmp_path):
        manifest_path = tmp_path / "vgg16_manifest.json"
        payload = {"concepts": {"concept_a": {"class_name": "cat", "layers": ["features.3"]}}}
        manifest_path.write_text(json.dumps(payload))
        result = recalib.load_model_manifest(str(manifest_path))
        assert result == payload


# ---------------------------------------------------------------------------
# build_class_concepts_map
# ---------------------------------------------------------------------------
@pytest.mark.unit
class TestBuildClassConceptsMap:
    def test_groups_concepts_by_matching_class_name(self):
        manifest_data = {
            "concepts": {
                "cat_spots": {"class_name": "cat"},
                "cat_ears": {"class_name": "cat"},
                "dog_collar": {"class_name": "dog"},
            }
        }
        class_names = ["bird", "cat", "dog"]  # alphabetically sorted, as get_class_folder_dicts does
        target_idx_list = [1, 2, 0]  # cat=1, dog=2, bird=0 (positional against TARGET_CLASS_LIST)
        result = recalib.build_class_concepts_map(manifest_data, class_names, target_idx_list)
        assert sorted(result[1]) == ["cat_ears", "cat_spots"]
        assert result[2] == ["dog_collar"]
        assert result[0] == []  # bird has no concepts in the manifest

    def test_empty_manifest_yields_empty_lists_for_every_target(self):
        result = recalib.build_class_concepts_map({}, ["cat", "dog"], [0, 1])
        assert result == {0: [], 1: []}

    def test_concept_with_unmatched_class_name_is_ignored(self):
        manifest_data = {"concepts": {"orphan": {"class_name": "not_a_real_class"}}}
        result = recalib.build_class_concepts_map(manifest_data, ["cat", "dog"], [0, 1])
        assert result == {0: [], 1: []}


# ---------------------------------------------------------------------------
# _resolve_layer_combos
# ---------------------------------------------------------------------------
@pytest.mark.unit
class TestResolveLayerCombos:
    def test_no_groups_three_layers_gives_seven_combos(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        combos = recalib._resolve_layer_combos(
            list(C.PROCESSED_LAYER_NAMES), use_groups=False, registry=registry, model_name="vgg16",
        )
        # C(3,1) + C(3,2) + C(3,3) = 3 + 3 + 1 = 7
        assert len(combos) == 7
        assert [C.PROCESSED_LAYER_NAMES[0]] in combos
        assert list(C.PROCESSED_LAYER_NAMES) in combos

    def test_no_groups_single_layer_gives_one_combo(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        combos = recalib._resolve_layer_combos(
            ["features.6"], use_groups=False, registry=registry, model_name="vgg16",
        )
        assert combos == [["features.6"]]

    def test_use_groups_with_no_manifest_groups_falls_back_to_combinations(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        combos = recalib._resolve_layer_combos(
            ["features.6"], use_groups=True, registry=registry, model_name="vgg16",
        )
        assert combos == [["features.6"]]

    def test_use_groups_with_matching_manifest_group_uses_its_layers(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        registry.save_layer_cav(
            model="vgg16", layer="features.3",
            concept_cavs={"concept_a": torch.zeros(8)},
            concept_aliases={"concept_a": "concept_a"},
        )
        registry.add_layer_group("mygroup", model="vgg16", layers=["features.3"])
        # layer_names is irrelevant once a matching group exists -- the group's own
        # layers list is used instead.
        combos = recalib._resolve_layer_combos(
            ["features.3", "features.5", "features.6"], use_groups=True, registry=registry, model_name="vgg16",
        )
        assert combos == [["features.3"]]


# ---------------------------------------------------------------------------
# _load_target_cavs / _load_class_concept_cavs
# ---------------------------------------------------------------------------
@pytest.mark.unit
class TestLoadTargetCavs:
    def test_found_cav_is_l2_normalized_and_reshaped_to_1xN(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        raw = torch.tensor([3.0, 4.0])  # norm = 5
        registry.save_layer_cav(
            model="vgg16", layer="features.3",
            concept_cavs={"concept_a": raw},
            concept_aliases={"concept_a": "concept_a"},
        )
        logger = _CollectingLogger()
        result = recalib._load_target_cavs(registry, "vgg16", ["features.3"], "concept_a", logger)
        assert set(result.keys()) == {"features.3"}
        cav = result["features.3"]
        assert cav.shape == (1, 2)
        assert torch.allclose(cav.norm(), torch.tensor(1.0), atol=1e-5)
        assert any(level == "info" for level, _ in logger.lines)

    def test_missing_concept_is_skipped_with_warning(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        logger = _CollectingLogger()
        result = recalib._load_target_cavs(registry, "vgg16", ["features.3"], "no_such_concept", logger)
        assert result == {}
        assert any(level == "warning" for level, _ in logger.lines)


@pytest.mark.unit
class TestLoadClassConceptCavs:
    def test_concepts_with_cavs_are_included_keyed_by_concept_name(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        registry.save_layer_cav(
            model="vgg16", layer="features.3",
            concept_cavs={"concept_a": torch.tensor([1.0, 0.0])},
            concept_aliases={"concept_a": "concept_a"},
        )
        logger = _CollectingLogger()
        result = recalib._load_class_concept_cavs(registry, "vgg16", ["features.3"], ["concept_a"], logger)
        assert set(result.keys()) == {"concept_a"}
        assert set(result["concept_a"].keys()) == {"features.3"}

    def test_concept_with_no_cavs_anywhere_is_omitted_with_warning(self, tmp_path):
        registry = CAVRegistry.create_empty_manifest(str(tmp_path / "cav_store"))
        logger = _CollectingLogger()
        result = recalib._load_class_concept_cavs(registry, "vgg16", ["features.3"], ["ghost_concept"], logger)
        assert result == {}
        assert any(level == "warning" for level, _ in logger.lines)


# ---------------------------------------------------------------------------
# CLI / integration tests (real subprocess invocations against pre-built CAV stores)
# ---------------------------------------------------------------------------
@pytest.mark.integration
@pytest.mark.slow
class TestMainRecalibCli:
    def test_missing_config_file_arg_errors_cleanly(self, run_script):
        result = run_script(
            "main_recalib_custom_by_loading_cav.py",
            ["--model_name", "vgg16", "--model_path", C.SINGLE_MODEL_ROOT],
        )
        assert result.returncode != 0
        assert "config_file" in result.stderr.lower()

    def test_nonexistent_config_file_path_errors_cleanly(self, run_script, tmp_path):
        bogus = str(tmp_path / "does_not_exist.yaml")
        result = run_script(
            "main_recalib_custom_by_loading_cav.py",
            [
                "--model_name", "vgg16",
                "--model_path", C.SINGLE_MODEL_ROOT,
                "--config_file", bogus,
                "--cav_store", C.SINGLE_CAV_STORE,
            ],
        )
        assert result.returncode != 0
        assert "Config file not found" in result.stderr

    def test_single_class_end_to_end(self, run_script, tmp_path, populated_single_cav_store):
        results_dir = str(tmp_path / "results")
        result = run_script(
            "main_recalib_custom_by_loading_cav.py",
            [
                "--model_name", C.MODEL_NAME,
                "--model_path", C.SINGLE_MODEL_ROOT,
                "--config_file", C.SINGLE_CONFIG_RECALIB_PATH,
                "--cav_store", populated_single_cav_store,
                "--store_results", results_dir,
            ],
            timeout=600,
        )
        result.assert_success()

        model_dir = os.path.join(results_dir, C.MODEL_NAME)
        assert os.path.isfile(os.path.join(model_dir, "accuracy_results_before.txt"))
        assert os.path.isfile(os.path.join(model_dir, f"layer_combinations_{C.MODEL_NAME}.txt"))
        assert os.path.isfile(os.path.join(model_dir, f"recalibration_combo_accuracy_{C.MODEL_NAME}.csv"))
        assert os.path.isfile(os.path.join(model_dir, f"recalibration_summary_{C.MODEL_NAME}.xlsx"))
        # At least one recalibrated model checkpoint (for the "cat" class, which owns the
        # only concept mapped to it via config.CONCEPT_FOLDER_LIST fallback).
        pth_files = [f for f in os.listdir(model_dir) if f.startswith("model_cls") and f.endswith(".pth")]
        assert pth_files, f"No recalibrated model checkpoints found in {model_dir}"

    def test_multiclass_joint_end_to_end(self, run_script, tmp_path, populated_multi_cav_store):
        results_dir = str(tmp_path / "results")
        result = run_script(
            "main_recalib_custom_by_loading_cav.py",
            [
                "--model_name", C.MODEL_NAME,
                "--model_path", C.MULTI_MODEL_ROOT,
                "--config_file", C.MULTI_CONFIG_RECALIB_PATH,
                "--cav_store", populated_multi_cav_store,
                "--store_results", results_dir,
                "--multiclass_recalibration_mode",
            ],
            timeout=600,
        )
        result.assert_success()
        assert "multiclass_recalibration_mode=True" in result.stdout

        model_dir = os.path.join(results_dir, C.MODEL_NAME)
        assert os.path.isfile(os.path.join(model_dir, "accuracy_results_before.txt"))
        assert os.path.isfile(
            os.path.join(model_dir, f"recalibration_multiclass_combo_accuracy_{C.MODEL_NAME}.csv")
        )
        assert os.path.isfile(os.path.join(model_dir, f"recalibration_summary_{C.MODEL_NAME}.xlsx"))
        pth_files = [f for f in os.listdir(model_dir) if f.startswith("model_multiclass_combo") and f.endswith(".pth")]
        assert pth_files, f"No joint recalibrated model checkpoints found in {model_dir}"
