misc:
  seed: 1234
classification:
  data_base_path: /home/srikanth/study1/RecalibrateNN/lean_recalibration/unit_test/data/classification/multiclass
  target_class_list:
  - cat
  - dog
  - bird
  linear_classifier_type: SGDClassifier
  lambda_aligns:
  - 0.0
  - 0.5
concept:
  base_path: /home/srikanth/study1/RecalibrateNN/lean_recalibration/unit_test/data/concepts/multiclass
  target_folders:
  - primary
  random_folder: /home/srikanth/study1/RecalibrateNN/lean_recalibration/unit_test/data/concepts/multiclass/random
hyperparameters:
  learning_rate: 0.001
  epochs: 1
  batch_size: 2
recalibration:
  override_retraining: true
  layers_to_train:
    vgg16:
    - features.6
    resnet50:
    - layer1
    inception_v3:
    - Mixed_5b
    mobilnet_v3_small:
    - features.1
    mobilenet_v3_large:
    - features.1
  lambda_aligns_recalib:
  - 0.5
xai_before_after:
  integrated_gradients: false
  grad_cam: false
  lime: false
  num_classes: 0
  class_images: {}
multiconcept:
  base_path: /home/srikanth/study1/RecalibrateNN/lean_recalibration/unit_test/data/concepts/multiclass
  random_folder_base_path: /home/srikanth/study1/RecalibrateNN/lean_recalibration/unit_test/data/concepts/multiclass
  random_folder: /home/srikanth/study1/RecalibrateNN/lean_recalibration/unit_test/data/concepts/multiclass/random
  class0:
    target_folders:
    - cat_spots
    - cat_ears
    random_folders:
    - random
    - random
  class1:
    target_folders:
    - dog_collar
    random_folders:
    - random
  class2:
    target_folders:
    - bird_feathers
    random_folders:
    - random
recalibration_weights:
  class0:
    class_weight: 1.0
    concept_weights:
      cat_spots: 0.5
      cat_ears: 0.5
  class1:
    class_weight: 1.0
    concept_weights:
      dog_collar: 1.0
  class2:
    class_weight: 1.0
    concept_weights:
      bird_feathers: 1.0
